development:
  client_id: bzBgRWq3GyMcGUD16F96PO2dLv4a
  client_secret: pn_fzjKl3L1hWf7H1nohuDshsjwa
  site: https://wso2is.local:9443
  authorize_url: /oauth2/authorize?prompt=login
  token_url: /oauth2/token
      
test:
  client_id: bzBgRWq3GyMcGUD16F96PO2dLv4a
  client_secret: pn_fzjKl3L1hWf7H1nohuDshsjwa
  site: https://wso2is.local:9443
  authorize_url: /oauth2/authorize?prompt=login
  token_url: /oauth2/token
  maintenance_username: maintenance
  maintenance_password: maintenance


production:
  client_id:
  client_secret:
  authorize_url:
  token_url:    
